theme: jekyll-theme-cayman
title: Welcome to the Girs Code homepage! 
description: We want to help you become a front-end developer, if you want to know how, read on or join us at our meetups in the National Museum of Computing in Bletchley Park. 
