theme: jekyll-theme-slate
title: Welcome to the Girs Code homepage! 
description: this is a sort of a Wiki page for the Girls Code Meetup that meets in the National Museum of Computing in Bletchley, Milton Keynes. 
